apiVersion: v1
kind: Secret
metadata:
  name: spt-secrets
type: Opaque

stringData:
  ANALYTICS_CODE: {{ .Values.secrets.analytics_code }}
  AUTH_CLIENT_ID: {{ .Values.secrets.auth_client_id }}
  AUTH_CLIENT_SECRET: {{ .Values.secrets.auth_client_secret }}
  POSTGRES_USER: {{ .Values.secrets.postgres_user }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres_password }}

data:
  JWT_TOKEN_KEY_PRIVATE: {{ .Values.secrets.jwt_token_key_private }}
